<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>SVG Math and Scientific reports in SVG/Html with zero-dependency</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>Math;Plot;Graph;Scientific;Reports;BarChart;PointPlot;Chart;SVG;HTML;C#;.NET</PackageTags>
		<PackageProjectUrl>https://github.com/samuel-vidal/Luminy</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Title>Luminy</Title>
		<Authors>Samuel Alexandre Vidal</Authors>
		<Copyright>Copyright (c) 2026 Samuel Alexandre Vidal</Copyright>
		<RepositoryUrl>https://github.com/samuel-vidal/Luminy.git</RepositoryUrl>
		<PackageReleaseNotes>First Release.</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Collections.Immutable" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.txt" Pack="true" PackagePath="\" />
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>


</Project>